backend = "glx";

shadow        = true;
shadow-radius = 12;
corner-radius = 3;

rules = (
  { match = "window_type = 'dock'"; opacity = 1.0; shadow = false; },
  { match = "window_type = 'tooltip'"; opacity = 1.0; shadow = true; }
);

animations = (
  {
    triggers = ["close"];
    preset = "disappear";
    duration = 0.16;
    scale = 0.5;
  },
  {
    triggers = ["open"];
    preset = "appear";
    duration = 0.16;
    scale = 0.5;
  }
);
