return {
	{ "nvim-treesitter/nvim-treesitter-textobjects", branch = "main" },
	{ "nvim-treesitter/nvim-treesitter-context" },
	{
		"nvim-treesitter/nvim-treesitter",
		lazy = false,
		build = ":TSUpdate",
		opts = {
			highlight = {
				enabled = true,
			},
			ensure_installed = {
				"c",
				"toml",
				"sql",
				"markdown",
				"markdown_inline",
				"python",
				"regex",
				"query",
				"tsx",
				"typescript",
				"yaml",
				"lua",
				"luadoc",
				"luap",
				"vim",
				"vimdoc",
				"xml",
				"printf",
				"html",
				"javascript",
				"json",
				"jsdoc",
				"diff",
				"c_sharp",
				"ocaml",
				"python",
			},
		},
	},
}
