# vim:fileencoding=utf-8:foldmethod=marker

include light.conf

# BEGIN_KITTY_FONTS
font_family      family="ProggyClean CE Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size              16.0
adjust_column_width    110%

window_padding_width   5
