local colors = _G.theme.colors

vim.api.nvim_set_hl(0, "FloatBorder", { bg = colors.black })

vim.api.nvim_set_hl(0, "WhichKeyNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "WhichKeyBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "WhichKeyTitle", { bg = colors.black })

vim.api.nvim_set_hl(0, "SnacksNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPicker", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerSearch", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerBoxTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerInputBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerInputSearch", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerInputTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksInputBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksInputTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksInputNormal", { bg = colors.black })

vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePromptNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePromptTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePreviewWrite", { bg = colors.black })

vim.api.nvim_set_hl(0, "BufferLineFill", { bg = colors.black })
vim.api.nvim_set_hl(0, "BufferLineBufferSelected", { bg = colors.black })
vim.api.nvim_set_hl(0, "BufferLineCloseButtonSelected", { bg = colors.black })
vim.api.nvim_set_hl(0, "BufferLineOffsetSeparator", { fg = colors.black })

vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "NeoTreeTabInactive", { bg = colors.black })
vim.api.nvim_set_hl(0, "NeoTreeTabSeparatorInactive", { bg = colors.black })
vim.api.nvim_set_hl(0, "NeoTreeTabSeparatorActive", { bg = colors.black })

vim.api.nvim_set_hl(0, "Pmenu", { bg = colors.black })
vim.api.nvim_set_hl(0, "BlinkCmpMenuSelection", { bg = colors.dark })
vim.api.nvim_set_hl(0, "BlinkCmpKind", { bg = colors.dark })
vim.api.nvim_set_hl(0, "BlinkCmpScrollBarThumb", { bg = colors.fg })
