local colors = _G.theme.colors

vim.api.nvim_set_hl(0, "FloatBorder", { bg = colors.black })

vim.api.nvim_set_hl(0, "WhichKeyNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "WhichKeyBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "WhichKeyTitle", { bg = colors.black })

vim.api.nvim_set_hl(0, "SnacksNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPicker", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerSearch", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerBoxTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerInputBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerInputSearch", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksPickerInputTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksInputBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksInputTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "SnacksInputNormal", { bg = colors.black })

vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePromptNormal", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePromptTitle", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", { bg = colors.black })
vim.api.nvim_set_hl(0, "TelescopePreviewWrite", { bg = colors.black })

-- vim.api.nvim_set_hl(0, "BufferLineBackground", { bg = colors.black })
vim.api.nvim_set_hl(0, "BufferLineFill", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineTab", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineTabSelected", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineTabSeparator", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineTabClose", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineBuffer", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineSeparatorSelected", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLinePickVisible", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineSepatorVisible", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineInfo", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineSeparator", { bg = colors.black })
vim.api.nvim_set_hl(0, "BufferLineBufferSelected", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineCloseButton", { bg = colors.black })
vim.api.nvim_set_hl(0, "BufferLineCloseButtonSelected", { bg = colors.black })
-- vim.api.nvim_set_hl(0, "BufferLineModifiedSelected", { bg = colors.white })
