vim.lsp.inlay_hint.enable(true)

vim.lsp.enable("gdscript")
vim.lsp.enable("postgres_lsp")
vim.lsp.enable("sqlls")
vim.lsp.enable("zls")
vim.lsp.enable("glsl_analyzer")
vim.lsp.enable("ocamlls")
vim.lsp.enable("asm_lsp")
vim.lsp.enable("elmls")
