# style defs

font "GohuFont uni 14 Nerd Font Mono"

gaps inner  5
gaps outer 10

default_border pixel 4

# class                 border  backgr. text    indicator child_border
client.focused          #96C2A1 #285577 #ffffff #96C2A1   #96C2A1
client.focused_inactive #333333 #333333 #ffffff #333333   #333333
client.unfocused        #333333 #333333 #888888 #333333   #333333
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

client.background       #ffffff
