hl.curve("spring", { type = "bezier", points = { { 0.7, -0.6 }, { 0.2, 1.4 } } })
hl.curve("snappy", { type = "bezier", points = { { 0.4, 1.5 }, { 0.6, 1.2 } } })
hl.curve("smooth", { type = "bezier", points = { { 0.33, 0.0 }, { 0.67, 1.0 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })
hl.curve("neon_glitch", { type = "bezier", points = { { -0.3, 2.0 }, { 1.7, -0.4 } } })
hl.curve("cyber_spike", { type = "bezier", points = { { 2.0, 0.0 }, { -1.0, 2.0 } } })
hl.curve("overdrive", { type = "bezier", points = { { 0.95, -0.5 }, { 0.05, 1.5 } } })
hl.curve("glitchwave", { type = "bezier", points = { { -0.5, 1.5 }, { 1.5, -0.5 } } })
hl.curve("pillowy", { type = "bezier", points = { { 0.2, 1.4 }, { 0.8, 0.6 } } })
hl.curve("floaty", { type = "bezier", points = { { 0.1, 0.9 }, { 0.9, 0.1 } } })
hl.curve("bubble_burst", { type = "bezier", points = { { 0.4, 1.6 }, { 0.6, -0.2 } } })
hl.curve("cushion", { type = "bezier", points = { { 0.05, 1.8 }, { 0.95, 0.3 } } })
hl.curve("soft_ripple", { type = "bezier", points = { { 0.3, 1.2 }, { 0.7, 0.8 } } })
hl.curve("jelly", { type = "bezier", points = { { 0.4, 1.6 }, { 0.6, -0.6 } } })
hl.curve("quantum", { type = "bezier", points = { { -0.5, 1.2 }, { 1.5, -0.5 } } })
hl.curve("flux_field", { type = "bezier", points = { { 1.2, -0.8 }, { -0.2, 1.7 } } })
hl.curve("pixel_burst", { type = "bezier", points = { { 0.8, -0.2 }, { 0.2, 1.8 } } })
hl.curve("phantom", { type = "bezier", points = { { 0.3, 0.8 }, { 0.7, 0.3 } } })
hl.curve("warp_wave", { type = "bezier", points = { { -0.8, 2.0 }, { 2.0, -0.8 } } })
hl.curve("cosmic_pulse", { type = "bezier", points = { { 0.5, -0.5 }, { 0.5, 1.5 } } })
hl.curve("echo_ripple", { type = "bezier", points = { { -0.2, 0.8 }, { 1.2, 0.2 } } })

hl.animation({ leaf = "workspaces", enabled = true, speed = 3, bezier = "smooth", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "smooth", style = "gnomed" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "smooth", style = "gnomed" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 3, bezier = "smooth", style = "slide" })
hl.animation({ leaf = "fade", enabled = false })
