hl.on("hyprland.start", function()
  hl.exec_cmd("gentoo-pipewire-launcher")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("~/.config/hypr/scripts/xdg-portal-hyprland")
end)
