monitor = ,1920x1200@60,0x0,1

exec-once = gentoo-pipewire-launcher
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr/scripts/xdg-portal-hyprland
