# melon — ported from hypr/hosts/melon.lua

exec gentoo-pipewire-launcher
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec ~/.config/sway/scripts/xdg-portal-sway
