# ~/figs/tmux/tmux.conf

## reload tmux config
bind R source-file '~/.tmux.conf'

# Open new windows in the current directory
bind c new-window -c "#{pane_current_path}"

# Open new panes in the current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

## Press Prefix + Z to source .zshrc in all panes of the current session
bind Z run 'panes=$(tmux list-panes -s -F "##{pane_id}"); \
            for pane in $panes; do \
              tmux send-keys -t "$pane" "exec zsh" Enter; \
            done'

bind -n M-Left  previous-window
bind -n M-Right next-window

set  -g mouse               on
set  -g base-index          1
set  -g renumber-windows    on
set  -g status-right-length 100
setw -g base-index          1

set -g pane-active-border-style "fg=#489c7a,bg=default"
set -g pane-border-style "fg=#489c7a,bg=default"

## plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-battery'

## supposedly to help with vim mode switching delay
set -s escape-time 0

## restore
set -g @resurrect-save         'S'
set -g @resurrect-restore      'R'

## battery
set -g @batt_color_status_primary_charged     'foreground'
set -g @batt_color_status_primary_charging    'foreground'
set -g @batt_color_status_primary_discharging 'foreground'
set -g @batt_color_status_primary_attached    'foreground'
set -g @batt_color_status_primary_unknown     'foreground'

set -g @batt_icon_charge_tier1    ''
set -g @batt_icon_charge_tier2    ''
set -g @batt_icon_charge_tier3    ''
set -g @batt_icon_charge_tier4    ''
set -g @batt_icon_charge_tier5    ''
set -g @batt_icon_charge_tier6    ''
set -g @batt_icon_charge_tier7    ''
set -g @batt_icon_charge_tier8    ''

set -g @batt_icon_status_charging '󱐋'
set -g @batt_icon_status_charged  '󱐋'

## status
# set -g @minimal-tmux-indicator-str "  • ﻌ •  "
# set -g @minimal-tmux-bg            "#5f8787"
set -g @minimal-tmux-indicator-str " · · · "
set -g @minimal-tmux-justify       "left"
set -g @minimal-tmux-bg            "#b3e0c5"
set -g @minimal-tmux-fg            "#000000"
set -g @minimal-tmux-status-right  "#{battery_color_status_bg}#{battery_icon} #{battery_percentage}#[default]  %d %b %Y  %H:%m  #S "



# install tpm if it's not already
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run '~/.config/tmux/plugins/tpm/tpm'
