set  -g mouse            on
set  -g base-index       1
setw -g base-index       1
set  -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'navahas/tmux-grimoire'
set -g @plugin 'robhurring/tmux-spotify'

set -g status-right-length 100


set -g @spotify_playing_icon '󰎋'
set -g @batt_icon_charge_tier1    ''
set -g @batt_icon_charge_tier2    ''
set -g @batt_icon_charge_tier3    ''
set -g @batt_icon_charge_tier4    ''
set -g @batt_icon_charge_tier5    ''
set -g @batt_icon_charge_tier6    ''
set -g @batt_icon_charge_tier7    ''
set -g @batt_icon_charge_tier8    ''
set -g @batt_icon_status_charging '󱐋'
set -g @batt_icon_status_charged  '󱐋'

# set -g @minimal-tmux-indicator-str "  • ﻌ •  "
set -g @minimal-tmux-indicator-str " ∘ ∘ ∘  "
set -g @minimal-tmux-justify       "left"
set -g @minimal-tmux-bg            "#3f6967"
set -g @minimal-tmux-fg            "#000000"
set -g @minimal-tmux-status-right  {
  "#{music_status} #{artist} : #{track} "
  " #{battery_color_fg}#{battery_icon} #{battery_percentage}#[default] "
  " %d %b %Y  %H:%m  #S "
}

bind-key -T prefix G run-shell "custom_shpell standard ncmpcpp \"ncmpcpp\""
set -g @shpell-ncmpcpp-color '#e3716e'
set -g @shpell-ncmpcpp-position 'right'
set -g @shpell-ncmpcpp-width '40%'
set -g @shpell-ncmpcpp-height '30%'

# install tpm if it's not already
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run '~/.config/tmux/plugins/tpm/tpm'
