typeset -U path

##
# VARIABLES
##
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
ZSH_COMPDUMP="${HOME}/.cache/zsh/zcompdump-${ZSH_VERSION}"
DISABLE_AUTO_UPDATE=true

# keys
source "$HOME/.keys"

# system context
source /etc/os-release

##
# EXPORTS
##
if [[ "$ID" == "arch" ]]; then
  export HOSTNAME=$(hostnamectl hostname | tr -d '\n')
elif [[ "$ID" == "gentoo" ]]; then
  export HOSTNAME=$(hostname)
fi

export ZSH="$HOME/.config/oh-my-zsh"
export ZSH_CUSTOM="$HOME/.config/oh-my-zsh/custom"
export EDITOR="/usr/bin/nvim"
export QT_QPA_PLATFORM="wayland"
export PYENV_ROOT="$HOME/.local/src/pyenv"
export FIGS="~/figs"
export QML_IMPORT_PATH=/usr/lib64/qt6/qml
export ZVM_PATH="$HOME/.local/zvm"
export ZVM_INSTALL="$HOME/.local/zvm/self"
export CARGO_HOME="$HOME/.local/cargo"

##
# PATH CONFIG
##
path+=("$HOME/.local/bin")
path+=("$HOME/go/bin")
path+=("$HOME/.local/cargo/bin")
path+=("$HOME/.local/zvm/self")
path+=("$HOME/.local/zvm/bin")
path+=("$HOME/.emacs.d/bin")
path+=("$PYENV_ROOT/bin")

##
# PLUGINS
##
plugins=(
  git fzf docker docker-compose
  eza colorize kitty urltools z
  zsh-autosuggestions zsh-syntax-highlighting
  zsh-completions ssh-agent colored-man-pages
)

##
# FUNCTIONS
##
function cdmk() {
  mkdir -p "$1" && cd "$1"
}

function vpn() {
  case "$1" in
    "up")
      wg-quick up vpn ;;
    "down")
      wg-quick down vpn ;;
    *)
      echo "unknown" ;;
  esac
}

function mcd() {
  mkdir -p "$1" && cd "$1"
}

##
# ALIASES
##
alias qmlls="qmlls6"
alias ssh="kitten ssh"
alias jq="jq -C"
alias jp="z"
alias setwall="awww img"

## emacs
alias et="emacsclient -t -a \"\""
alias emacs="emacsclient -t -a \"\""
alias dom="emacsclient -t -a \"\""

# cd to dir in clipboard (needs to be grabbed from yazi keybind cd)
alias yazii="yazi && cd $(wl-paste)"



##
## MISC
##
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.config/oh-my-zsh}/custom}/plugins/zsh-completions/src
[[ -d $(dirname "$ZSH_COMPDUMP") ]] || mkdir -p $(dirname "$ZSH_COMPDUMP")
autoload -U compinit && compinit
source $ZSH/oh-my-zsh.sh

eval "$(starship init zsh)"
eval "$(pyenv init - zsh)"

# Point apps (ProtonVPN keyring, Secret Service) at the user D-Bus session bus
# export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/bus"

# ocaml
[[ ! -r '/home/june/.opam/opam-init/init.zsh' ]] || source '/home/june/.opam/opam-init/init.zsh' > /dev/null 2> /dev/null
