typeset -U path

# VARIABLES
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
ZSH_COMPDUMP="${HOME}/.cache/zsh/zcompdump-${ZSH_VERSION}"
DISABLE_AUTO_UPDATE=true

# keys
source "$HOME/.keys"

# system context
source /etc/os-release

# EXPORTS
if [[ "$ID" == "arch" ]]; then
  export HOSTNAME=$(hostnamectl hostname | tr -d '\n')
elif [[ "$ID" == "gentoo" ]]; then
  export HOSTNAME=$(hostname)
fi

export ZSH="$HOME/.config/oh-my-zsh"
export ZSH_CUSTOM="$HOME/.config/oh-my-zsh/custom"
export EDITOR="/usr/bin/nvim"
export QT_QPA_PLATFORM="xcb"
export PYENV_ROOT="$HOME/.local/src/pyenv"
export FIGS="~/figs"

export ZVM_PATH="$HOME/.local/zvm"
export ZVM_INSTALL="$HOME/.local/zvm/self"

# PATH CONFIG
path+=("$HOME/.local/cargo/bin")
path+=("$HOME/go/bin")
path+=("$HOME/.local/bin")
path+=("$HOME/.local/zvm/self")
path+=("$HOME/.local/zvm/bin")
path+=("$PYENV_ROOT/bin")

# PLUGINS
plugins=(
  git fzf docker docker-compose
  eza colorize kitty urltools z
  zsh-autosuggestions zsh-syntax-highlighting
  zsh-completions ssh-agent colored-man-pages
)

# ALIASES
alias setwall="awww img"
alias ssh="kitten ssh"
alias jq="jq -C"
alias qmlls="qmlls6"
alias cj="z"
alias makeport="nvim /etc/portage/make.conf"

function vpn() {
  case "$1" in
    "up")
      wg-quick up vpn ;;
    "down")
      wg-quick down vpn ;;
    *)
      echo "unknown" ;;
  esac
}

function mcd() {
  mkdir -p "$1" && cd "$1"
}

fpath+=${ZSH_CUSTOM:-${ZSH:-~/.config/oh-my-zsh}/custom}/plugins/zsh-completions/src
[[ -d $(dirname "$ZSH_COMPDUMP") ]] || mkdir -p $(dirname "$ZSH_COMPDUMP")
autoload -U compinit && compinit
source $ZSH/oh-my-zsh.sh

eval "$(starship init zsh)"
eval "$(pyenv init - zsh)"

